---
### For reference, see `nextepc.conf`

logger:
  file: /usr/local/var/log/open5gs/smf.log
  trace:
    app: 1
    diameter: 1
    gtpv2: 1
    gtp: 1

smf:
  freeDiameter:
    identity: smf.localdomain
    realm: localdomain
    listen_on: 192.168.26.40
    no_fwd: true
    load_extension:
      - module: /freeDiameter/dbg_msg_dumps.fdx
        conf: 0x8888
      - module: /freeDiameter/dict_rfc5777.fdx
      - module: /freeDiameter/dict_mip6i.fdx
      - module: /freeDiameter/dict_nasreq.fdx
      - module: /freeDiameter/dict_nas_mipv6.fdx
      - module: /freeDiameter/dict_dcca.fdx
      - module: /freeDiameter/dict_dcca_3gpp.fdx
    connect:
      - identity: pcrf.localdomain
        addr: 192.168.26.50
  gtpc:
    - addr: 192.168.26.40
  gtpu:
    - addr: 192.168.26.40
  pfcp:
    - addr: 192.168.26.40
  subnet:
    - addr: 10.10.0.1/16
      apn: internet
      dev: ogstap
    - addr: 10.11.0.1/16
      apn: internet2
      dev: ogstap2
    - addr: 10.12.0.1/16
      apn: internet3
      dev: ogstap3
  dns:
    - 8.8.8.8
    - 8.8.4.4

upf:
  pfcp:
    - addr: 192.168.27.41
      apn: [internet, internet2, internet3]
