[project]
name = "daedalus-5g"
version = "0.11.2.dev"
description = "A tool for creating 4G/5G environments both with SDRs and virtual simulation to run experiments in"
authors = [
    { name = "cglewis", email = "clewis@iqt.org" }
]
license = { file = "LICENSE" }
readme = "README.md"
requires-python = ">=3.6"

classifiers = [
    "Development Status :: 2 - Pre-Alpha",
    "License :: OSI Approved :: Apache Software License",
    "Programming Language :: Python"
]
# Requirements
dependencies = [
    "docker == 6.0.1",
    "docker-compose == 1.29.2",
    "dovesnap == 1.1.4",
    "plumbum == 1.7.2",
    "inquirer == 2.10.0",
]

[project.optional-dependencies]
test = [
    "attrs==22.1.0",
    "codecov==2.1.12",
    "pylint==2.15.2",
    "pytype==2022.10.13",
    "pytest==7.1.3",
    "pytest-cov==4.0.0",
    "ruamel.yaml==0.17.21"
]
generate_fs = [
    "essential_generators",
    "numpy"
]
confuser = [
    "fusepy"
]

[project.scripts]
daedalus = "daedalus.__main__:main"

[build-system]
requires = [
    "setuptools >= 62.0.0",
]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = [ "daedalus" ]
package-dir = {"daedalus" = "5G/daedalus"}
include-package-data = true

[tool.setuptools.package-data]
daedalus = ["5G/*",]

